version: '3'

services:
  sitl_1:
    image: ardupilot_docker
    container_name: sitl_1
    network_mode: host
    volumes:
      - ./simulator_generated_files/param_files:/root/home/param_files
      - ./simulator_generated_files/sitl_settings:/root/home/sitl_settings
    command: >
      /bin/bash -c "export $$(cat /root/home/sitl_settings/default_sim_settings_copter1) &&
                    /home/ardupilot/Tools/autotest/sim_vehicle.py --vehicle $${VEHICLE} -m --daemon -w --custom-location=$${LAT},$${LON},$${ALT},$${DIR} --no-rebuild -I1 --add-param-file=/root/home/param_files/default_params_copter1.param"

  mavros1:
    depends_on:
      - sitl_1
      - mavlink_router
    network_mode: host
    image: grantphllps/mavros_docker
    container_name: mavros_1
    stdin_open: true
    tty: true
    volumes:
      - ./simulator_generated_files/mavros_envs:/root/home/env_files
    command: >
      /bin/bash -c "source /home/catkin_ws/devel/setup.bash &&
                    export $$(cat /root/home/env_files/env1)
                    roslaunch mavros apm.launch fcu_url:=$${PORT} tgt_system:=$${SYS_ID} tgt_component:=$${COMP_ID}"

  sitl_2:
    image: ardupilot_docker
    container_name: sitl_2
    network_mode: host
    volumes:
      - ./simulator_generated_files/param_files:/root/home/param_files
      - ./simulator_generated_files/sitl_settings:/root/home/sitl_settings
    command: >
      /bin/bash -c "export $$(cat /root/home/sitl_settings/default_sim_settings_copter2) &&
                    /home/ardupilot/Tools/autotest/sim_vehicle.py --vehicle $${VEHICLE} -m --daemon -w --custom-location=$${LAT},$${LON},$${ALT},$${DIR} --no-rebuild -I2 --add-param-file=/root/home/param_files/default_params_copter2.param"

  mavros2:
    depends_on:
      - sitl_2
      - mavlink_router
    network_mode: host
    image: grantphllps/mavros_docker
    container_name: mavros_2
    stdin_open: true
    tty: true
    volumes:
      - ./simulator_generated_files/mavros_envs:/root/home/env_files
    command: >
      /bin/bash -c "source /home/catkin_ws/devel/setup.bash &&
                    export $$(cat /root/home/env_files/env2)
                    roslaunch --wait mavros apm.launch fcu_url:=$${PORT} tgt_system:=$${SYS_ID} tgt_component:=$${COMP_ID}"

  mavlink_router:
    image: grantphllps/mavlink_router
    container_name: mavlink_router
    depends_on:
      - sitl_1
      - sitl_2
    stdin_open: true
    tty: true
    network_mode: "host"
    volumes:
      - ./simulator_generated_files/mavlink_router:/root/home/mavlink_router_files
    command: >
      /bin/bash -c "mavlink-routerd -c /root/home/mavlink_router_files/main.conf"