version: '3'

services:
  sitl_1:
    image: grantphllps/ardupilot
    container_name: sitl_1
    network_mode: host
    volumes:
      - ./env_files:/root/home/env_files
    command: >
      /bin/bash -c "export $$(cat /root/home/env_files/env1) &&
                    /home/ardupilot/Tools/autotest/sim_vehicle.py --vehicle $${VEHICLE} -w --custom-location=$${LAT},$${LON},$${ALT},$${DIR} --no-rebuild -I1 --add-param-file=/home/ardupilot/Tools/autotest/default_params/gazebo-drone1.parm"

  mavlink_router:
    image: grantphllps/mavlink_router
    container_name: mavlink_router
    depends_on:
      - sitl_1
    stdin_open: true
    tty: true
    network_mode: "host"
    volumes:
      - ./mavlink_router:/root/home/mavlink_router_files
    command: >
      /bin/bash -c "mavlink-routerd -c /root/home/mavlink_router_files/main.conf"