version: '3'

services:
  sitl_1:
    image: ardupilot_docker
    container_name: sitl_1
    network_mode: host
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./simulator_generated_files/param_files:/root/home/param_files
      - ./simulator_generated_files/sitl_settings:/root/home/sitl_settings
      - ./simulator_generated_files/vehicleinfo/vehicleinfo.py:/home/ardupilot/Tools/autotest/pysim/vehicleinfo.py

    command: > 
      "/bin/bash"
    # command: >
    #   /bin/bash -c "/home/ardupilot/Tools/autotest/sim_vehicle.py -v ArduCopter -f gazebo-drone1 -m '--daemon --streamrate=-1'"
    # command: >
    #   /bin/bash -c "export $$(cat /root/home/sitl_settings/default_sim_settings_copter1) &&
    #                 /home/ardupilot/Tools/autotest/sim_vehicle.py --vehicle $${VEHICLE} -m '--daemon --streamrate=-1' -w --custom-location=$${LAT},$${LON},$${ALT},$${DIR} --no-rebuild -I1 --add-param-file=/root/home/param_files/default_params_copter1.param -f gazebo-drone1"


  # mavlink_router:
  #   image: grantphllps/mavlink_router
  #   container_name: mavlink_router
  #   depends_on:
  #     - sitl_1
  #   stdin_open: true
  #   tty: true
  #   network_mode: "host"
  #   volumes:
  #     - ./simulator_generated_files/mavlink_router:/root/home/mavlink_router_files
  #   command: >
  #     /bin/bash -c "mavlink-routerd -c /root/home/mavlink_router_files/main.conf"