version: '3'

services:
  sitl_1:
    image: ardupilot_docker
    container_name: sitl_1
    network_mode: host
    volumes:
      - ./simulator_generated_files/param_files:/root/home/param_files
      - ./simulator_generated_files/sitl_settings:/root/home/sitl_settings
      - ./simulator_generated_files/vehicleinfo/vehicleinfo.py:/home/ardupilot/Tools/autotest/pysim/vehicleinfo.py
      - ./simulator_generated_files/param_files/default_params_copter1.param:/home/ardupilot/Tools/autotest/default_params/gazebo-drone1.parm
    command: >
      /bin/bash -c "export $$(cat /root/home/sitl_settings/default_sim_settings_copter1) &&
                    /home/ardupilot/Tools/autotest/sim_vehicle.py --vehicle $${VEHICLE} -m '--daemon --streamrate=-1' -w --custom-location=$${LAT},$${LON},$${ALT},$${DIR} --no-rebuild -I0 --add-param-file=/root/home/param_files/default_params_copter1.param"

  hrl_1:
    depends_on:
      - sitl_1
      - mavlink_router
    network_mode: host
    image: hrl_docker
    container_name: hrl_1
    stdin_open: true
    tty: true
    volumes:
      - ./simulator_generated_files/hrl_envs:/root/home/env_files
    command: >
      /bin/bash -c "source /home/catkin_ws/devel/setup.bash &&
                    export $$(cat /root/home/env_files/env1)
                    roslaunch hrl_control hrl_control.launch"

  sitl_2:
    image: ardupilot_docker
    container_name: sitl_2
    network_mode: host
    volumes:
      - ./simulator_generated_files/param_files:/root/home/param_files
      - ./simulator_generated_files/sitl_settings:/root/home/sitl_settings
      - ./simulator_generated_files/vehicleinfo/vehicleinfo.py:/home/ardupilot/Tools/autotest/pysim/vehicleinfo.py
      - ./simulator_generated_files/param_files/default_params_copter2.param:/home/ardupilot/Tools/autotest/default_params/gazebo-drone2.parm
    command: >
      /bin/bash -c "export $$(cat /root/home/sitl_settings/default_sim_settings_copter2) &&
                    /home/ardupilot/Tools/autotest/sim_vehicle.py --vehicle $${VEHICLE} -m '--daemon --streamrate=-1' -w --custom-location=$${LAT},$${LON},$${ALT},$${DIR} --no-rebuild -I1 --add-param-file=/root/home/param_files/default_params_copter2.param"

  hrl_2:
    depends_on:
      - sitl_2
      - mavlink_router
    network_mode: host
    image: hrl_docker
    container_name: hrl_2
    stdin_open: true
    tty: true
    volumes:
      - ./simulator_generated_files/hrl_envs:/root/home/env_files
    command: >
      /bin/bash -c "source /home/catkin_ws/devel/setup.bash &&
                    export $$(cat /root/home/env_files/env2)
                    roslaunch --wait hrl_control hrl_control.launch"

  sitl_3:
    image: ardupilot_docker
    container_name: sitl_3
    network_mode: host
    volumes:
      - ./simulator_generated_files/param_files:/root/home/param_files
      - ./simulator_generated_files/sitl_settings:/root/home/sitl_settings
      - ./simulator_generated_files/vehicleinfo/vehicleinfo.py:/home/ardupilot/Tools/autotest/pysim/vehicleinfo.py
      - ./simulator_generated_files/param_files/default_params_copter3.param:/home/ardupilot/Tools/autotest/default_params/gazebo-drone3.parm
    command: >
      /bin/bash -c "export $$(cat /root/home/sitl_settings/default_sim_settings_copter3) &&
                    /home/ardupilot/Tools/autotest/sim_vehicle.py --vehicle $${VEHICLE} -m '--daemon --streamrate=-1' -w --custom-location=$${LAT},$${LON},$${ALT},$${DIR} --no-rebuild -I2 --add-param-file=/root/home/param_files/default_params_copter3.param"

  hrl_3:
    depends_on:
      - sitl_3
      - mavlink_router
    network_mode: host
    image: hrl_docker
    container_name: hrl_3
    stdin_open: true
    tty: true
    volumes:
      - ./simulator_generated_files/hrl_envs:/root/home/env_files
    command: >
      /bin/bash -c "source /home/catkin_ws/devel/setup.bash &&
                    export $$(cat /root/home/env_files/env3)
                    roslaunch --wait hrl_control hrl_control.launch"

  sitl_4:
    image: ardupilot_docker
    container_name: sitl_4
    network_mode: host
    volumes:
      - ./simulator_generated_files/param_files:/root/home/param_files
      - ./simulator_generated_files/sitl_settings:/root/home/sitl_settings
      - ./simulator_generated_files/vehicleinfo/vehicleinfo.py:/home/ardupilot/Tools/autotest/pysim/vehicleinfo.py
      - ./simulator_generated_files/param_files/default_params_copter4.param:/home/ardupilot/Tools/autotest/default_params/gazebo-drone4.parm
    command: >
      /bin/bash -c "export $$(cat /root/home/sitl_settings/default_sim_settings_copter4) &&
                    /home/ardupilot/Tools/autotest/sim_vehicle.py --vehicle $${VEHICLE} -m '--daemon --streamrate=-1' -w --custom-location=$${LAT},$${LON},$${ALT},$${DIR} --no-rebuild -I3 --add-param-file=/root/home/param_files/default_params_copter4.param"

  hrl_4:
    depends_on:
      - sitl_4
      - mavlink_router
    network_mode: host
    image: hrl_docker
    container_name: hrl_4
    stdin_open: true
    tty: true
    volumes:
      - ./simulator_generated_files/hrl_envs:/root/home/env_files
    command: >
      /bin/bash -c "source /home/catkin_ws/devel/setup.bash &&
                    export $$(cat /root/home/env_files/env4)
                    roslaunch --wait hrl_control hrl_control.launch"

  sitl_5:
    image: ardupilot_docker
    container_name: sitl_5
    network_mode: host
    volumes:
      - ./simulator_generated_files/param_files:/root/home/param_files
      - ./simulator_generated_files/sitl_settings:/root/home/sitl_settings
      - ./simulator_generated_files/vehicleinfo/vehicleinfo.py:/home/ardupilot/Tools/autotest/pysim/vehicleinfo.py
      - ./simulator_generated_files/param_files/default_params_copter5.param:/home/ardupilot/Tools/autotest/default_params/gazebo-drone5.parm
    command: >
      /bin/bash -c "export $$(cat /root/home/sitl_settings/default_sim_settings_copter5) &&
                    /home/ardupilot/Tools/autotest/sim_vehicle.py --vehicle $${VEHICLE} -m '--daemon --streamrate=-1' -w --custom-location=$${LAT},$${LON},$${ALT},$${DIR} --no-rebuild -I4 --add-param-file=/root/home/param_files/default_params_copter5.param"

  hrl_5:
    depends_on:
      - sitl_5
      - mavlink_router
    network_mode: host
    image: hrl_docker
    container_name: hrl_5
    stdin_open: true
    tty: true
    volumes:
      - ./simulator_generated_files/hrl_envs:/root/home/env_files
    command: >
      /bin/bash -c "source /home/catkin_ws/devel/setup.bash &&
                    export $$(cat /root/home/env_files/env5)
                    roslaunch --wait hrl_control hrl_control.launch"

  sitl_6:
    image: ardupilot_docker
    container_name: sitl_6
    network_mode: host
    volumes:
      - ./simulator_generated_files/param_files:/root/home/param_files
      - ./simulator_generated_files/sitl_settings:/root/home/sitl_settings
      - ./simulator_generated_files/vehicleinfo/vehicleinfo.py:/home/ardupilot/Tools/autotest/pysim/vehicleinfo.py
      - ./simulator_generated_files/param_files/default_params_copter6.param:/home/ardupilot/Tools/autotest/default_params/gazebo-drone6.parm
    command: >
      /bin/bash -c "export $$(cat /root/home/sitl_settings/default_sim_settings_copter6) &&
                    /home/ardupilot/Tools/autotest/sim_vehicle.py --vehicle $${VEHICLE} -m '--daemon --streamrate=-1' -w --custom-location=$${LAT},$${LON},$${ALT},$${DIR} --no-rebuild -I5 --add-param-file=/root/home/param_files/default_params_copter6.param"

  hrl_6:
    depends_on:
      - sitl_6
      - mavlink_router
    network_mode: host
    image: hrl_docker
    container_name: hrl_6
    stdin_open: true
    tty: true
    volumes:
      - ./simulator_generated_files/hrl_envs:/root/home/env_files
    command: >
      /bin/bash -c "source /home/catkin_ws/devel/setup.bash &&
                    export $$(cat /root/home/env_files/env6)
                    roslaunch --wait hrl_control hrl_control.launch"

  sitl_7:
    image: ardupilot_docker
    container_name: sitl_7
    network_mode: host
    volumes:
      - ./simulator_generated_files/param_files:/root/home/param_files
      - ./simulator_generated_files/sitl_settings:/root/home/sitl_settings
      - ./simulator_generated_files/vehicleinfo/vehicleinfo.py:/home/ardupilot/Tools/autotest/pysim/vehicleinfo.py
      - ./simulator_generated_files/param_files/default_params_copter7.param:/home/ardupilot/Tools/autotest/default_params/gazebo-drone7.parm
    command: >
      /bin/bash -c "export $$(cat /root/home/sitl_settings/default_sim_settings_copter7) &&
                    /home/ardupilot/Tools/autotest/sim_vehicle.py --vehicle $${VEHICLE} -m '--daemon --streamrate=-1' -w --custom-location=$${LAT},$${LON},$${ALT},$${DIR} --no-rebuild -I6 --add-param-file=/root/home/param_files/default_params_copter7.param"

  hrl_7:
    depends_on:
      - sitl_7
      - mavlink_router
    network_mode: host
    image: hrl_docker
    container_name: hrl_7
    stdin_open: true
    tty: true
    volumes:
      - ./simulator_generated_files/hrl_envs:/root/home/env_files
    command: >
      /bin/bash -c "source /home/catkin_ws/devel/setup.bash &&
                    export $$(cat /root/home/env_files/env7)
                    roslaunch --wait hrl_control hrl_control.launch"

  sitl_8:
    image: ardupilot_docker
    container_name: sitl_8
    network_mode: host
    volumes:
      - ./simulator_generated_files/param_files:/root/home/param_files
      - ./simulator_generated_files/sitl_settings:/root/home/sitl_settings
      - ./simulator_generated_files/vehicleinfo/vehicleinfo.py:/home/ardupilot/Tools/autotest/pysim/vehicleinfo.py
      - ./simulator_generated_files/param_files/default_params_copter8.param:/home/ardupilot/Tools/autotest/default_params/gazebo-drone8.parm
    command: >
      /bin/bash -c "export $$(cat /root/home/sitl_settings/default_sim_settings_copter8) &&
                    /home/ardupilot/Tools/autotest/sim_vehicle.py --vehicle $${VEHICLE} -m '--daemon --streamrate=-1' -w --custom-location=$${LAT},$${LON},$${ALT},$${DIR} --no-rebuild -I7 --add-param-file=/root/home/param_files/default_params_copter8.param"

  hrl_8:
    depends_on:
      - sitl_8
      - mavlink_router
    network_mode: host
    image: hrl_docker
    container_name: hrl_8
    stdin_open: true
    tty: true
    volumes:
      - ./simulator_generated_files/hrl_envs:/root/home/env_files
    command: >
      /bin/bash -c "source /home/catkin_ws/devel/setup.bash &&
                    export $$(cat /root/home/env_files/env8)
                    roslaunch --wait hrl_control hrl_control.launch"

  mavlink_router:
    image: grantphllps/mavlink_router
    container_name: mavlink_router
    depends_on:
      - sitl_1
      - sitl_2
      - sitl_3
      - sitl_4
      - sitl_5
      - sitl_6
      - sitl_7
      - sitl_8
    stdin_open: true
    tty: true
    network_mode: "host"
    volumes:
      - ./simulator_generated_files/mavlink_router:/root/home/mavlink_router_files
    command: >
      /bin/bash -c "mavlink-routerd -c /root/home/mavlink_router_files/main.conf"