version: '3'

services:
  sitl_1:
    image: grantphllps/ardupilot
    container_name: sitl_1
    network_mode: host
    volumes:
      - ./env_files:/root/home/env_files
    command: >
      /bin/bash -c "export $$(cat /root/home/env_files/env1) &&
                    /home/ardupilot/Tools/autotest/sim_vehicle.py --vehicle $${VEHICLE} -w --custom-location=$${LAT},$${LON},$${ALT},$${DIR} --no-rebuild -I1 --add-param-file=/home/ardupilot/Tools/autotest/default_params/gazebo-drone1.parm"

  clustering_1:
    depends_on:
      - sitl_1
      - mavlink_router
    network_mode: host
    image: grantphllps/mavros_docker
    container_name: clustering_1
    stdin_open: true
    tty: true
    volumes:
      - ./env_files:/root/home/env_files
    command: >
      /bin/bash -c "source /home/catkin_ws/devel/setup.bash &&
                    export $$(cat /root/home/env_files/ros_env1)
                    roslaunch mavros apm.launch fcu_url:=$${PORT} tgt_system:=$${SYS_ID} tgt_component:=$${COMP_ID}"

  sitl_2:
    image: grantphllps/ardupilot
    container_name: sitl_2
    network_mode: host
    volumes:
      - ./env_files:/root/home/env_files
    command: >
      /bin/bash -c "export $$(cat /root/home/env_files/env2) &&
                    /home/ardupilot/Tools/autotest/sim_vehicle.py --vehicle $${VEHICLE} -w --custom-location=$${LAT},$${LON},$${ALT},$${DIR} --no-rebuild -I2 --add-param-file=/home/ardupilot/Tools/autotest/default_params/gazebo-drone2.parm"

  clustering_2:
    depends_on:
      - sitl_2
      - mavlink_router
    network_mode: host
    image: grantphllps/mavros_docker
    container_name: clustering_2
    stdin_open: true
    tty: true
    volumes:
      - ./env_files:/root/home/env_files
    command: >
      /bin/bash -c "source /home/catkin_ws/devel/setup.bash &&
                    export $$(cat /root/home/env_files/ros_env2)
                    roslaunch --wait mavros apm.launch fcu_url:=$${PORT} tgt_system:=$${SYS_ID} tgt_component:=$${COMP_ID}"

  sitl_3:
    image: grantphllps/ardupilot
    container_name: sitl_3
    network_mode: host
    volumes:
      - ./env_files:/root/home/env_files
    command: >
      /bin/bash -c "export $$(cat /root/home/env_files/env3) &&
                    /home/ardupilot/Tools/autotest/sim_vehicle.py --vehicle $${VEHICLE} -w --custom-location=$${LAT},$${LON},$${ALT},$${DIR} --no-rebuild -I3 --add-param-file=/home/ardupilot/Tools/autotest/default_params/gazebo-drone3.parm"

  clustering_3:
    depends_on:
      - sitl_3
      - mavlink_router
    network_mode: host
    image: grantphllps/mavros_docker
    container_name: clustering_3
    stdin_open: true
    tty: true
    volumes:
      - ./env_files:/root/home/env_files
    command: >
      /bin/bash -c "source /home/catkin_ws/devel/setup.bash &&
                    export $$(cat /root/home/env_files/ros_env3)
                    roslaunch --wait mavros apm.launch fcu_url:=$${PORT} tgt_system:=$${SYS_ID} tgt_component:=$${COMP_ID}"

  sitl_4:
    image: grantphllps/ardupilot
    container_name: sitl_4
    network_mode: host
    volumes:
      - ./env_files:/root/home/env_files
    command: >
      /bin/bash -c "export $$(cat /root/home/env_files/env4) &&
                    /home/ardupilot/Tools/autotest/sim_vehicle.py --vehicle $${VEHICLE} -w --custom-location=$${LAT},$${LON},$${ALT},$${DIR} --no-rebuild -I4 --add-param-file=/home/ardupilot/Tools/autotest/default_params/gazebo-drone4.parm"

  clustering_4:
    depends_on:
      - sitl_4
      - mavlink_router
    network_mode: host
    image: grantphllps/mavros_docker
    container_name: clustering_4
    stdin_open: true
    tty: true
    volumes:
      - ./env_files:/root/home/env_files
    command: >
      /bin/bash -c "source /home/catkin_ws/devel/setup.bash &&
                    export $$(cat /root/home/env_files/ros_env4)
                    roslaunch --wait mavros apm.launch fcu_url:=$${PORT} tgt_system:=$${SYS_ID} tgt_component:=$${COMP_ID}"

  mavlink_router:
    image: grantphllps/mavlink_router
    container_name: mavlink_router
    depends_on:
      - sitl_1
      - sitl_2
      - sitl_3
      - sitl_4
    stdin_open: true
    tty: true
    network_mode: "host"
    volumes:
      - ./mavlink_router:/root/home/mavlink_router_files
    command: >
      /bin/bash -c "mavlink-routerd -c /root/home/mavlink_router_files/main.conf"